name: Muehle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: actions/setup-docker@v2
        with:
          dockerfile: Dockerfile

      - name: Build and test with Docker
        run: |
          docker build -t mill .
          docker run -it --rm \
            -e DISPLAY=$DISPLAY \
            -v /tmp/.X11-unix:/tmp/.X11-unix \
            mill sbt test

  scalatest_sbt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: sbt clean coverage test
      - name: Coverage Report
        run: sbt coverageReport
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.0.0
