name: Muehle

on:
  push:
    branches: [ main ]

jobs:
  scalatest_sbt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: sbt clean coverage test
      - name: Coverage Report
        run: sbt coverageReport
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.0.0
