name: Scala CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [8, 11, 16]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
    - name: Restore sbt dependencies
      uses: actions/cache@v2
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ matrix.java }}-${{ hashFiles('**/build.sbt') }}
        restore-keys: |
          ${{ runner.os }}-sbt-${{ matrix.java }}-
          ${{ runner.os }}-sbt-
    - name: Restore Ivy dependencies
      uses: actions/cache@v2
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-ivy-${{ matrix.java }}-${{ hashFiles('**/ivy.xml') }}
        restore-keys: |
          ${{ runner.os }}-ivy-${{ matrix.java }}-
          ${{ runner.os }}-ivy-
    - name: Compile
      run: sbt compile
    - name: Run tests
      run: sbt test
    - name: Static code analysis
      run: sbt scalafix --check
  coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Restore sbt dependencies
      uses: actions/cache@v2
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ matrix.java }}-${{ hashFiles('**/build.sbt') }}
        restore-keys: |
          ${{ runner.os }}-sbt-${{ matrix.java }}-
          ${{ runner.os }}-sbt-
    - name: Restore Ivy dependencies
      uses: actions/cache@v2
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-ivy-${{ matrix.java }}-${{ hashFiles('**/ivy.xml') }}
                restore-keys
