name: Muehle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  scalatest_sbt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
      - run: |
        docker build -t mill .
        docker run -it --rm \
          -e DISPLAY=$DISPLAY \
          -v /tmp/.X11-unix:/tmp/.X11-unix \
          -t mill sbt test
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.0.0
